### ISSUE TITLE
Trait to abstract over different readers

### ISSUE THREAD

**Issue by dignifiedquire** [Majored/rs-async-zip#21]
It would be nice if there was a trait that abstracted over the different implementations of readers, such that I can implement generically over them.

**Comment by Majored** [comment]
Would you be able to elaborate on this a bit more?

I've been struggling for a while to come up with a decent API for this crate. The current one works well documentation-wise but results in naming conflicts if you're importing more than one reader in the same file (and just general confusion since they're all separate structs but named the same).

I've also tried out a type-based API (where there's a single struct which is abstract over some method, and relevant methods are only implemented for that concrete type - eg. ZipFileReader<SeekMethod<File>>) which is really practical and works well, but is a nightmare documentation-wise.

**Comment by Majored** [comment]
I'll go ahead and close this but will continue to put thought into it.
