### ISSUE TITLE
make filename an owned type

### ISSUE THREAD

**Issue by softprops** [Majored/rs-async-zip#3]
I'm finding is a bit hard to use this library when I need to parse more than a single zip given a single &'static str value. This library seems to work great but only the the case were you have a hard coded filename. As soon as you try to read input from a user interface you run into lifetime errors. not being able to create a &'static str from owned String types. 

This would go away if filename were and owned type. Though I could be missing something. If it is possible today can you share some examples were collecting a list of paths of even a single path from user input is possible?

**Comment by Majored** [comment]
There's no actual explicit 'static lifetime, but likely an implicit one due to being placed on the heap (Arc/Box). Heck, even my own example for the read::fs module puts it on the heap.

So given that, and the fact that the whole point of read::fs is to be parallel, making it an owned string is really the only option I can see as well. I could use a Cow, but to make that work, we'd have to make the caller pass a pre-constructed Cow and decide whether it be borrowed or owned. That doesn't feel like a good API design to me.

I'll get this done when I next go to work on this crate. 👍

**Comment by softprops** [comment]
Thanks. For what it’s worth it’s less the lifetime constraints of this crate that it is the async ecosystem.

Following the example code functions like tokio::spawn require static lifetimes

https://github.com/Majored/rs-async-zip/blob/eae278980fd1663533653035eb18ede865beda97/examples/fs_parallel_extract.rs#L24

**Comment by Majored** [comment]
Actually, coming back to this, I'm going to make it an owned string as you suggest.
No point in adding the complexity with Cow & two different constructors for the sake of a single allocation.
