### ISSUE TITLE
`ZipEntryReader` no longer provides `compare_crc`

### ISSUE THREAD

**Issue by NobodyXu** [Majored/rs-async-zip#62]
In 0.0.9, `ZipEntryReader` provides method to manually check crc so that we can use `AsyncRead` impl to read from it and then check the crc.

With 0.0.10, this is no longer possible.

**Comment by Majored** [comment]
Just playing around trying to work out a good API really.

For instance, I thought it would be a good idea to remove the ZipEntryReader's dependency on having an associated ZipEntry, but it turns out 0.0.9's API actually worked much better since this dependency resulted in a disjoint borrow of the fields when opening the entry reader. 

Because of this change, in 0.0.10, it's no longer possible to hold a reference to a ZipEntry and hold a ZipEntryReader, which makes things really awkward. So I definitely want to work on something better or just straight up reverse that change.

**Comment by NobodyXu** [comment]
Actually I would like `ZipFileReader::done` to check the c2c automatically instead of having some special methods like `ZipEntryReader::read_to_end_c2c` to do it.

**Comment by NobodyXu** [comment]
@Majored Can we add c2c checking to `ZipFileReader::done` please?

Also I would really like a new release for the bug fix and the improvements.

**Comment by NobodyXu** [comment]
Method [`async_zip::ZipEntry::crc32`](https://docs.rs/async_zip/latest/async_zip/struct.ZipEntry.html#method.crc32) can be used to check crc32 checksum, so I will close this as completed.

**Comment by NobodyXu** [comment]
Turns out that we still need to compute the crc32 checksum ourselves.

But since `async_zip` already computes the checksum internally, I would like it to be reused instead.
