### ISSUE TITLE
What is "internally stored ZIP archives"?

### ISSUE THREAD

**Issue by NobodyXu** [Majored/rs-async-zip#63]
From [`async_zip::read::stream`#considerations](https://docs.rs/async_zip/latest/async_zip/read/stream/index.html#considerations):

> The inability to read internally stored ZIP archives when using the Stored compression method.

What does "internally stored ZIP archives" mean?

**Comment by skairunner** [comment]
When reading a zip file that contains another zip file, with Store & via the streaming method.

I can't say for sure whether this limitation still exists, but that is my reading of the quoted bit.

**Comment by Majored** [comment]
As above, with the added condition that both entries were using data descriptors which I should've mentioned. Whilst I haven't added data descriptor reading back to stream reader yet, it definitely is my intention to. In this case, we'd match the inner ZIP file's data descriptor signature first rather than the outer ZIP file's one.

**Comment by NobodyXu** [comment]
Oh I see, so in the streaming mode async-zip might mistake the inner zip's metadata as the outer zip's metadata.
That actually sounds like a serious issue that is impossible to resolve in the streaming mode.

Luckily, in my use case, it is unlikely for this to happen, but still a bit worry some.

**Comment by NobodyXu** [comment]
Thanks for the explanation, I will close this issue.
