### ISSUE TITLE
`ZipEntryReader::read_to_*_checked` is unusable

### ISSUE THREAD

**Issue by NobodyXu** [Majored/rs-async-zip#83]
Both of them takes a mutable alias to `self` and an immutable reference to `ZipEntry`:

```rust
    pub async fn read_to_end_checked(&mut self, buf: &mut Vec<u8>, entry: &ZipEntry) -> Result<usize>;
    pub async fn read_to_string_checked(&mut self, buf: &mut String, entry: &ZipEntry) -> Result<usize>;
```

The mutable alias to `self` can only be obtained if we also hold a mutable alias to `ZipFileReader`.
But to hold an immutable reference to `ZipEntry`, we need to hold an immutable reference to `ZipFileReader`.

Thus, this API is unusable.

**Comment by Majored** [comment]
Yep, this wasn't something I ran into until after I had already switched over the API so didn't realise the implications at the time. That's why, unfortunately, the README example currently clones the ZipEntry to make it at least somewhat usable.

Whilst I wasn't a big fan of the old API (where a ZipEntryReader holds a reference to the ZipEntry itself), it worked well since there was a disjoint/split borrow on the ZipFileReader's fields.

Will hopefully tackle switching it back soon but feel free to do so if you happen to have the time.

**Comment by NobodyXu** [comment]
> Whilst I wasn't a big fan of the old API (where a ZipEntryReader holds a reference to the ZipEntry itself), it worked well since there was a disjoint/split borrow on the ZipFileReader's fields.

I have another idea of fixing this, by adding a new API to ZipFileReader:

    pub fn entry_and_reader(&mut self) -> (&ZipEntry, &mut ZipEntryReader<...>);

**Comment by moutikabdessabour** [comment]
Please make this clear in the documentation. something as simple as creating an iterator over the entries and checking if the filename is in a list and then decompressing doesn't work because of the issue highlighted in the first comment.

**Comment by Majored** [comment]
I've had a bit of time to play around and I quite like @NobodyXu's suggestion. 

What I've come up with is a type-driven approach in order to have compile-time guarantees about what methods can be called, rather than just having `read_to_*_checked` error or panic if it doesn't have an associated entry.

Readers now implement two entry reader methods:
https://github.com/Majored/rs-async-zip/blob/846ec137907d70f96f93d08c96277f0ec7b788d0/src/base/read/seek.rs#L84
https://github.com/Majored/rs-async-zip/blob/846ec137907d70f96f93d08c96277f0ec7b788d0/src/base/read/seek.rs#L98


This still needs a bit of polish but the documentation page would essentially look like this: https://imgur.com/a/HRQkGvr
Where the `read_to_*_checked()` methods are only defined on the WithEntry variant and no longer require it as a parameter.

I'm happy to settle on this unless anyone else has any other suggestions.

**Comment by Majored** [comment]
I've just pushed V0.0.15 which has the above changes - I'll go ahead and close this as a result. 👍
